services:
  mysql:
    image: mysql:8.0
    container_name: healthcare-db
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: healthcare_system
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: